version: '3'

services:
  app-staging:
    build: 
      context: .
    container_name: api-whatsapp-dev
    env_file: .env
    ports: 
      - "8004:8004"
    networks: 
      - nginx
    restart: always
networks:
  nginx:
    external: true
